### ISSUE TITLE
Tic Tac Toe

### ISSUE THREAD

**Issue by chinmayr633** [ayush-raj13/mini-projects#92]
hi,
 Its a tic tac toe game built using Ruby language.
please assign me

**Comment by chinmayr633** [comment]
Where should i put this project?

**Comment by ayush-raj13** [comment]
Create a separate directory named Ruby, inside that create another folder named Tic-Tac-Toe. Keep your files inside this folder

**Comment by ayush-raj13** [comment]
Fixed in PR #100
