### ISSUE TITLE
Quote Generator

### ISSUE THREAD

**Issue by shrinidhihegde3** [ayush-raj13/mini-projects#93]
It is a complete HTML,CSS,JS website for generating random quote with their author

**Comment by shrinidhihegde3** [comment]
Hey, @ayush-raj13 ,Pls assign this issue to me..

**Comment by shrinidhihegde3** [comment]
Where should i put this project?

**Comment by ayush-raj13** [comment]
Put this inside JavaScript directory

**Comment by shrinidhihegde3** [comment]
hey @ayush-raj13, I have created pull request pls check.

**Comment by ayush-raj13** [comment]
Sorry for the delay @shrinidhihegde3

**Comment by ayush-raj13** [comment]
Fixed in PR #94
